local util = require("tests.util")
local vim = vim
describe("loading ogmarks", function()
    before_each(function() util:delAllBuf(vim) end)
    it("should load a mark from an existing database", function()
        local config = util:defaultConfig("should load a mark from an existing database")
        config.db.file = "tests/dbs/lorem_line_4.db"
        local og = require("ogmarks")(config)
        og:focusOgMark(1)
        assert.are.same("mea ad idque decore docendi.", vim.fn.getline("."))
    end)

    it("should jump back and forth between marks on the same buffer", function()
        local config = util:defaultConfig("should jump back and forth between marks on the same buffer")
        config.db.file ="tests/dbs/lorem_line_4_8_10.db"
        local og = require("ogmarks")(config)
        og:focusOgMark(1)
        assert.are.same("mea ad idque decore docendi.", vim.fn.getline("."))
        og:focusOgMark(2)
        assert.are.same("tincidunt. Ad exerci aperiam mel, ludus choro mediocrem sea ea, nec tacimates iudicabit in.", vim.fn.getline("."))
        og:focusOgMark(3)
        assert.are.same("Probo dicunt accusamus ei ius, quem error nullam ea sea, nam an blandit iracundia. Et mel latine probatus postulant. Amet zril cu mel, ea mea tempor sententiae, an reque gubergren nam.", vim.fn.getline("."))
    end)

    it("should jump between buffers", function()
        local config = util:defaultConfig("should jump between buffers")
        local og = require("ogmarks")(config)
        util:openTextFile(vim, "ll.txt")
        vim.cmd("norm G")
        og:createOgMarkAtCurPos()
        util:openTextFile(vim, "lorem.txt")
        vim.cmd("norm gg4j")
        og:createOgMarkAtCurPos()
        util:openTextFile(vim, "countries.txt")
        vim.cmd("norm gg20j")
        og:createOgMarkAtCurPos()
        og:focusOgMark(1)
        assert.are.same("drwxrwxr-x 4 og og 4.0K Jan 23 22:12 ../", vim.fn.getline("."))
        og:focusOgMark(3)
        assert.are.same("Bolivia", vim.fn.getline("."))
        og:focusOgMark(2)
        assert.are.same("Postea oblique nam ex. Eum dictas eirmod ex, ut putant malorum liberavisse eos. Utamur officiis maiestatis qui cu, ne diam augue possit sed. ", vim.fn.getline("."))
    end)
end)
